ignored = ["github.com/google/protobuf/examples/tutorial"]

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/websocket"

[[constraint]]
  branch = "master"
  name = "github.com/gorilla/handlers"

[[constraint]]
  branch = "master"
  name = "github.com/ttacon/libphonenumber"

[[constraint]]
  branch = "master"
  name = "github.com/golang-migrate/migrate"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  version = "1.3.1"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "google.golang.org/genproto"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.10.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.5.0"

[[constraint]]
  name = "github.com/nats-io/gnatsd"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/jinzhu/gorm"

[prune]
  go-tests = true
  unused-packages = true
