// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth_service.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthenticateRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_097c5545847ae0db, []int{0}
}
func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (dst *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(dst, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AuthenticateResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_097c5545847ae0db, []int{1}
}
func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (dst *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(dst, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

type SmsCodeCheckRequest struct {
	Phone                string   `protobuf:"bytes,1,opt,name=phone" json:"phone,omitempty"`
	Code                 string   `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCodeCheckRequest) Reset()         { *m = SmsCodeCheckRequest{} }
func (m *SmsCodeCheckRequest) String() string { return proto.CompactTextString(m) }
func (*SmsCodeCheckRequest) ProtoMessage()    {}
func (*SmsCodeCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_097c5545847ae0db, []int{2}
}
func (m *SmsCodeCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCodeCheckRequest.Unmarshal(m, b)
}
func (m *SmsCodeCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCodeCheckRequest.Marshal(b, m, deterministic)
}
func (dst *SmsCodeCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCodeCheckRequest.Merge(dst, src)
}
func (m *SmsCodeCheckRequest) XXX_Size() int {
	return xxx_messageInfo_SmsCodeCheckRequest.Size(m)
}
func (m *SmsCodeCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCodeCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCodeCheckRequest proto.InternalMessageInfo

func (m *SmsCodeCheckRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *SmsCodeCheckRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SmsCodeCheckResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	UserId               uint64   `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsCodeCheckResponse) Reset()         { *m = SmsCodeCheckResponse{} }
func (m *SmsCodeCheckResponse) String() string { return proto.CompactTextString(m) }
func (*SmsCodeCheckResponse) ProtoMessage()    {}
func (*SmsCodeCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_auth_service_097c5545847ae0db, []int{3}
}
func (m *SmsCodeCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsCodeCheckResponse.Unmarshal(m, b)
}
func (m *SmsCodeCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsCodeCheckResponse.Marshal(b, m, deterministic)
}
func (dst *SmsCodeCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsCodeCheckResponse.Merge(dst, src)
}
func (m *SmsCodeCheckResponse) XXX_Size() int {
	return xxx_messageInfo_SmsCodeCheckResponse.Size(m)
}
func (m *SmsCodeCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsCodeCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SmsCodeCheckResponse proto.InternalMessageInfo

func (m *SmsCodeCheckResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *SmsCodeCheckResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *SmsCodeCheckResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "api.AuthenticateRequest")
	proto.RegisterType((*AuthenticateResponse)(nil), "api.AuthenticateResponse")
	proto.RegisterType((*SmsCodeCheckRequest)(nil), "api.SmsCodeCheckRequest")
	proto.RegisterType((*SmsCodeCheckResponse)(nil), "api.SmsCodeCheckResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AuthServiceClient is the client API for AuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AuthServiceClient interface {
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error)
	SmsCodeCheck(ctx context.Context, in *SmsCodeCheckRequest, opts ...grpc.CallOption) (*SmsCodeCheckResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateResponse, error) {
	out := new(AuthenticateResponse)
	err := c.cc.Invoke(ctx, "/api.AuthService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) SmsCodeCheck(ctx context.Context, in *SmsCodeCheckRequest, opts ...grpc.CallOption) (*SmsCodeCheckResponse, error) {
	out := new(SmsCodeCheckResponse)
	err := c.cc.Invoke(ctx, "/api.AuthService/SmsCodeCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthServiceServer is the server API for AuthService service.
type AuthServiceServer interface {
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateResponse, error)
	SmsCodeCheck(context.Context, *SmsCodeCheckRequest) (*SmsCodeCheckResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AuthService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_SmsCodeCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsCodeCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).SmsCodeCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.AuthService/SmsCodeCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).SmsCodeCheck(ctx, req.(*SmsCodeCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthService_Authenticate_Handler,
		},
		{
			MethodName: "SmsCodeCheck",
			Handler:    _AuthService_SmsCodeCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth_service.proto",
}

func init() { proto.RegisterFile("auth_service.proto", fileDescriptor_auth_service_097c5545847ae0db) }

var fileDescriptor_auth_service_097c5545847ae0db = []byte{
	// 304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0x41, 0x4e, 0xeb, 0x30,
	0x14, 0x54, 0xda, 0xfe, 0x7e, 0x78, 0x74, 0x81, 0xdc, 0x02, 0xa1, 0x20, 0x81, 0x2c, 0x16, 0xa8,
	0xa8, 0x0d, 0x82, 0x5d, 0x37, 0x08, 0x75, 0xc5, 0xb6, 0x3d, 0x40, 0x31, 0xc9, 0x53, 0x63, 0x95,
	0xf8, 0x99, 0xd8, 0xe9, 0x01, 0xb8, 0x02, 0x47, 0xe3, 0x02, 0x2c, 0x38, 0x08, 0xb2, 0x13, 0x50,
	0x8a, 0x22, 0x76, 0x6f, 0xfc, 0xc6, 0x33, 0x9e, 0x31, 0x30, 0x51, 0xd8, 0x74, 0x69, 0x30, 0xdf,
	0xc8, 0x18, 0x27, 0x3a, 0x27, 0x4b, 0xac, 0x2d, 0xb4, 0x1c, 0x9e, 0xae, 0x88, 0x56, 0xcf, 0x18,
	0x09, 0x2d, 0x23, 0xa1, 0x14, 0x59, 0x61, 0x25, 0x29, 0x53, 0x52, 0xf8, 0x15, 0xf4, 0xef, 0x0b,
	0x9b, 0xa2, 0xb2, 0x32, 0x16, 0x16, 0xe7, 0xf8, 0x52, 0xa0, 0xb1, 0x6c, 0x00, 0xff, 0x74, 0x4a,
	0x0a, 0xc3, 0xe0, 0x3c, 0xb8, 0xdc, 0x9d, 0x97, 0x80, 0x1f, 0xc2, 0x60, 0x9b, 0x6c, 0x34, 0x29,
	0x83, 0xfc, 0x0e, 0xfa, 0x8b, 0xcc, 0xcc, 0x28, 0xc1, 0x59, 0x8a, 0xf1, 0xfa, 0x4f, 0x11, 0xc6,
	0xa0, 0x13, 0x53, 0x82, 0x61, 0xdb, 0x1f, 0xfa, 0x99, 0x0b, 0x18, 0x6c, 0x0b, 0x94, 0xc2, 0x4e,
	0xc1, 0xd2, 0x1a, 0xd5, 0xb7, 0x82, 0x07, 0x6c, 0x08, 0x3b, 0x85, 0xc1, 0x5c, 0x89, 0x0c, 0xc3,
	0x96, 0x5f, 0xfc, 0x60, 0x76, 0x04, 0xff, 0xdd, 0xbc, 0x94, 0x89, 0x37, 0xe8, 0xcc, 0xbb, 0x0e,
	0x3e, 0x24, 0x37, 0x1f, 0x01, 0xec, 0xb9, 0xc7, 0x2f, 0xca, 0x86, 0xd8, 0x23, 0xf4, 0xea, 0x59,
	0x58, 0x38, 0x11, 0x5a, 0x4e, 0x1a, 0xba, 0x18, 0x1e, 0x37, 0x6c, 0xaa, 0xe0, 0x27, 0xaf, 0xef,
	0x9f, 0x6f, 0xad, 0x03, 0xbe, 0x1f, 0x6d, 0xae, 0x23, 0x51, 0x63, 0x4c, 0x83, 0x11, 0x23, 0xe8,
	0xd5, 0x43, 0x55, 0x0e, 0x0d, 0x45, 0x55, 0x0e, 0x4d, 0x0d, 0xf0, 0x91, 0x77, 0xb8, 0xe0, 0x67,
	0xbf, 0x1d, 0x22, 0x93, 0x99, 0xb1, 0x2b, 0x6f, 0x1c, 0xbb, 0x0b, 0xd3, 0x60, 0xf4, 0xd4, 0xf5,
	0x5f, 0x7a, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xbf, 0x6e, 0xe9, 0x0b, 0x02, 0x00, 0x00,
}
