// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game_service.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_rpc "google.golang.org/genproto/googleapis/rpc/status"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type JoinPoolRequest struct {
}

func (m *JoinPoolRequest) Reset()                    { *m = JoinPoolRequest{} }
func (m *JoinPoolRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinPoolRequest) ProtoMessage()               {}
func (*JoinPoolRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type JoinPoolResponse struct {
	Game *Game `protobuf:"bytes,1,opt,name=game" json:"game,omitempty"`
}

func (m *JoinPoolResponse) Reset()                    { *m = JoinPoolResponse{} }
func (m *JoinPoolResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinPoolResponse) ProtoMessage()               {}
func (*JoinPoolResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *JoinPoolResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type SendMoveRequest struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Command string `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Board   string `protobuf:"bytes,3,opt,name=board" json:"board,omitempty"`
}

func (m *SendMoveRequest) Reset()                    { *m = SendMoveRequest{} }
func (m *SendMoveRequest) String() string            { return proto.CompactTextString(m) }
func (*SendMoveRequest) ProtoMessage()               {}
func (*SendMoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *SendMoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SendMoveRequest) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *SendMoveRequest) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

type SendMoveResponse struct {
}

func (m *SendMoveResponse) Reset()                    { *m = SendMoveResponse{} }
func (m *SendMoveResponse) String() string            { return proto.CompactTextString(m) }
func (*SendMoveResponse) ProtoMessage()               {}
func (*SendMoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type ReceiveMoveRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReceiveMoveRequest) Reset()                    { *m = ReceiveMoveRequest{} }
func (m *ReceiveMoveRequest) String() string            { return proto.CompactTextString(m) }
func (*ReceiveMoveRequest) ProtoMessage()               {}
func (*ReceiveMoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ReceiveMoveRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReceiveMoveResponse struct {
	Status  *google_rpc.Status `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
	Command string             `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Board   string             `protobuf:"bytes,3,opt,name=board" json:"board,omitempty"`
}

func (m *ReceiveMoveResponse) Reset()                    { *m = ReceiveMoveResponse{} }
func (m *ReceiveMoveResponse) String() string            { return proto.CompactTextString(m) }
func (*ReceiveMoveResponse) ProtoMessage()               {}
func (*ReceiveMoveResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *ReceiveMoveResponse) GetStatus() *google_rpc.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReceiveMoveResponse) GetCommand() string {
	if m != nil {
		return m.Command
	}
	return ""
}

func (m *ReceiveMoveResponse) GetBoard() string {
	if m != nil {
		return m.Board
	}
	return ""
}

type Game struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	RedUser   *User  `protobuf:"bytes,2,opt,name=red_user,json=redUser" json:"red_user,omitempty"`
	BlackUser *User  `protobuf:"bytes,3,opt,name=black_user,json=blackUser" json:"black_user,omitempty"`
}

func (m *Game) Reset()                    { *m = Game{} }
func (m *Game) String() string            { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()               {}
func (*Game) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Game) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Game) GetRedUser() *User {
	if m != nil {
		return m.RedUser
	}
	return nil
}

func (m *Game) GetBlackUser() *User {
	if m != nil {
		return m.BlackUser
	}
	return nil
}

type User struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func init() {
	proto.RegisterType((*JoinPoolRequest)(nil), "api.JoinPoolRequest")
	proto.RegisterType((*JoinPoolResponse)(nil), "api.JoinPoolResponse")
	proto.RegisterType((*SendMoveRequest)(nil), "api.SendMoveRequest")
	proto.RegisterType((*SendMoveResponse)(nil), "api.SendMoveResponse")
	proto.RegisterType((*ReceiveMoveRequest)(nil), "api.ReceiveMoveRequest")
	proto.RegisterType((*ReceiveMoveResponse)(nil), "api.ReceiveMoveResponse")
	proto.RegisterType((*Game)(nil), "api.Game")
	proto.RegisterType((*User)(nil), "api.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GameService service

type GameServiceClient interface {
	JoinPool(ctx context.Context, in *JoinPoolRequest, opts ...grpc.CallOption) (*JoinPoolResponse, error)
	SendMove(ctx context.Context, in *SendMoveRequest, opts ...grpc.CallOption) (*SendMoveResponse, error)
	ReceiveMove(ctx context.Context, in *ReceiveMoveRequest, opts ...grpc.CallOption) (GameService_ReceiveMoveClient, error)
}

type gameServiceClient struct {
	cc *grpc.ClientConn
}

func NewGameServiceClient(cc *grpc.ClientConn) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) JoinPool(ctx context.Context, in *JoinPoolRequest, opts ...grpc.CallOption) (*JoinPoolResponse, error) {
	out := new(JoinPoolResponse)
	err := grpc.Invoke(ctx, "/api.GameService/JoinPool", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SendMove(ctx context.Context, in *SendMoveRequest, opts ...grpc.CallOption) (*SendMoveResponse, error) {
	out := new(SendMoveResponse)
	err := grpc.Invoke(ctx, "/api.GameService/SendMove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) ReceiveMove(ctx context.Context, in *ReceiveMoveRequest, opts ...grpc.CallOption) (GameService_ReceiveMoveClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GameService_serviceDesc.Streams[0], c.cc, "/api.GameService/ReceiveMove", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameServiceReceiveMoveClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GameService_ReceiveMoveClient interface {
	Recv() (*ReceiveMoveResponse, error)
	grpc.ClientStream
}

type gameServiceReceiveMoveClient struct {
	grpc.ClientStream
}

func (x *gameServiceReceiveMoveClient) Recv() (*ReceiveMoveResponse, error) {
	m := new(ReceiveMoveResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GameService service

type GameServiceServer interface {
	JoinPool(context.Context, *JoinPoolRequest) (*JoinPoolResponse, error)
	SendMove(context.Context, *SendMoveRequest) (*SendMoveResponse, error)
	ReceiveMove(*ReceiveMoveRequest, GameService_ReceiveMoveServer) error
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_JoinPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).JoinPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameService/JoinPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).JoinPool(ctx, req.(*JoinPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SendMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SendMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.GameService/SendMove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SendMove(ctx, req.(*SendMoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_ReceiveMove_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReceiveMoveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServiceServer).ReceiveMove(m, &gameServiceReceiveMoveServer{stream})
}

type GameService_ReceiveMoveServer interface {
	Send(*ReceiveMoveResponse) error
	grpc.ServerStream
}

type gameServiceReceiveMoveServer struct {
	grpc.ServerStream
}

func (x *gameServiceReceiveMoveServer) Send(m *ReceiveMoveResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JoinPool",
			Handler:    _GameService_JoinPool_Handler,
		},
		{
			MethodName: "SendMove",
			Handler:    _GameService_SendMove_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveMove",
			Handler:       _GameService_ReceiveMove_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game_service.proto",
}

func init() { proto.RegisterFile("game_service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xcd, 0x8a, 0x13, 0x41,
	0x10, 0x26, 0x93, 0xb8, 0x9b, 0x54, 0xc0, 0x5d, 0xdb, 0x95, 0x0c, 0xc3, 0x2e, 0x48, 0xb3, 0x87,
	0x65, 0x61, 0x67, 0xd6, 0x78, 0xf3, 0x05, 0x04, 0x41, 0xd0, 0x09, 0x7a, 0xf1, 0xb0, 0x74, 0xa6,
	0x6b, 0x43, 0x6b, 0xa6, 0x6b, 0xb6, 0x7b, 0x32, 0x17, 0xf1, 0xe2, 0x2b, 0xf8, 0x16, 0xbe, 0x8e,
	0xaf, 0xe0, 0x83, 0x48, 0xff, 0x24, 0x31, 0x09, 0x08, 0xde, 0xa6, 0xaa, 0xbe, 0xfe, 0xbe, 0xaa,
	0xfa, 0x6a, 0x80, 0x2d, 0x44, 0x8d, 0x77, 0x16, 0x4d, 0xa7, 0x2a, 0xcc, 0x1b, 0x43, 0x2d, 0xb1,
	0xbe, 0x68, 0x54, 0x76, 0xbe, 0x20, 0x5a, 0x2c, 0xb1, 0x10, 0x8d, 0x2a, 0x84, 0xd6, 0xd4, 0x8a,
	0x56, 0x91, 0xb6, 0x01, 0x92, 0x4d, 0x62, 0xd5, 0x34, 0x55, 0x61, 0x5b, 0xd1, 0xae, 0x62, 0x81,
	0x3f, 0x81, 0x93, 0x37, 0xa4, 0xf4, 0x3b, 0xa2, 0x65, 0x89, 0x0f, 0x2b, 0xb4, 0x2d, 0x7f, 0x01,
	0xa7, 0xdb, 0x94, 0x6d, 0x48, 0x5b, 0x64, 0x17, 0x30, 0x70, 0xc2, 0x69, 0xef, 0x79, 0xef, 0x6a,
	0x3c, 0x1d, 0xe5, 0xa2, 0x51, 0xf9, 0x6b, 0x51, 0x63, 0xe9, 0xd3, 0xfc, 0x3d, 0x9c, 0xcc, 0x50,
	0xcb, 0xb7, 0xd4, 0x61, 0x64, 0x61, 0x8f, 0x21, 0x51, 0xd2, 0xe3, 0x47, 0x65, 0xa2, 0x24, 0x4b,
	0xe1, 0xb8, 0xa2, 0xba, 0x16, 0x5a, 0xa6, 0x89, 0x4f, 0xae, 0x43, 0x76, 0x06, 0x8f, 0xe6, 0x24,
	0x8c, 0x4c, 0xfb, 0x3e, 0x1f, 0x02, 0xce, 0xe0, 0x74, 0x4b, 0x19, 0xba, 0xe0, 0x97, 0xc0, 0x4a,
	0xac, 0x50, 0x75, 0xf8, 0x0f, 0x25, 0xfe, 0x00, 0x4f, 0x77, 0x50, 0x71, 0x84, 0x6b, 0x38, 0x0a,
	0x93, 0xc7, 0x21, 0x58, 0x1e, 0x76, 0x92, 0x9b, 0xa6, 0xca, 0x67, 0xbe, 0x52, 0x46, 0xc4, 0x7f,
	0x37, 0x7b, 0x0f, 0x03, 0xb7, 0x8d, 0x83, 0xa1, 0x2f, 0x61, 0x68, 0x50, 0xde, 0xad, 0x2c, 0x1a,
	0x4f, 0xb4, 0x5e, 0xdd, 0x07, 0x8b, 0xa6, 0x3c, 0x36, 0x28, 0xdd, 0x07, 0xbb, 0x02, 0x98, 0x2f,
	0x45, 0xf5, 0x25, 0xe0, 0xfa, 0xfb, 0xb8, 0x91, 0x2f, 0xba, 0x4f, 0x3e, 0x85, 0x81, 0x7f, 0xb1,
	0xd5, 0x19, 0x78, 0x9d, 0x0c, 0x86, 0xee, 0xad, 0x76, 0x16, 0x85, 0x86, 0x37, 0xf1, 0xf4, 0x67,
	0x02, 0x63, 0xd7, 0xdc, 0x2c, 0xdc, 0x0c, 0xfb, 0x08, 0xc3, 0xb5, 0xbd, 0xec, 0xcc, 0xab, 0xec,
	0x1d, 0x40, 0xf6, 0x6c, 0x2f, 0x1b, 0xb7, 0x7f, 0xf1, 0xfd, 0xd7, 0xef, 0x1f, 0xc9, 0x84, 0xb3,
	0xa2, 0xbb, 0x2d, 0x9c, 0xed, 0xc5, 0x67, 0x52, 0xfa, 0xa6, 0x21, 0x5a, 0xbe, 0xea, 0x5d, 0xb3,
	0x4f, 0x30, 0x5c, 0x1b, 0x16, 0x79, 0xf7, 0x4e, 0x22, 0xf2, 0x1e, 0xb8, 0xca, 0x3d, 0xef, 0x39,
	0x9f, 0x6c, 0x78, 0xbf, 0x2a, 0xf9, 0xad, 0xb0, 0xa8, 0xe5, 0x4d, 0x4d, 0x1d, 0x3a, 0xf2, 0x7b,
	0x18, 0xff, 0xe5, 0x29, 0x9b, 0x78, 0xa6, 0xc3, 0x5b, 0xc8, 0xd2, 0xc3, 0xc2, 0xae, 0x0a, 0xcb,
	0x76, 0x55, 0x4c, 0x80, 0x7a, 0xa1, 0xdb, 0xde, 0xfc, 0xc8, 0xff, 0x15, 0x2f, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x8d, 0x5b, 0x89, 0x67, 0x03, 0x00, 0x00,
}
